#!/usr/bin/env python3
"""Generate crawlable product showcase HTML during the site build."""

from __future__ import annotations

import json
import re
import shutil
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Callable
from urllib.error import HTTPError, URLError
from urllib.parse import urlencode, urlsplit
from urllib.request import Request, urlopen


PAGE_SIZE = 50
UUID_PATTERN = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
    re.IGNORECASE,
)
GENERATED_MARKER = "<!-- generated by scripts/generate_product_showcase_pages.py; do not edit -->"
USER_AGENT = "NexscopeProductShowcaseBuilder/1.0"


class BuildError(RuntimeError):
    """Raised when static product pages cannot be built safely."""


def config_value(config: str, name: str) -> str:
    match = re.search(rf"^{re.escape(name)}:\s*(.+?)\s*$", config, re.MULTILINE)
    if not match:
        raise BuildError(f"Missing {name} in docs/_config.yml")
    return match.group(1).strip().strip("'\"")


def load_settings(source_dir: Path) -> tuple[str, str, str]:
    config = (source_dir / "_config.yml").read_text(encoding="utf-8")
    api_base = config_value(config, "product_showcase_api_base").rstrip("/")
    site_url = config_value(config, "url").rstrip("/")
    baseurl = config_value(config, "baseurl").strip()
    if baseurl and not baseurl.startswith("/"):
        baseurl = "/" + baseurl
    baseurl = baseurl.rstrip("/")
    for label, value in (("product_showcase_api_base", api_base), ("url", site_url)):
        parsed = urlsplit(value)
        if parsed.scheme != "https" or not parsed.netloc:
            raise BuildError(f"{label} must be an absolute HTTPS URL")
    return api_base, site_url, baseurl


def request_text(url: str, accept: str) -> str:
    request = Request(url, headers={"Accept": accept, "User-Agent": USER_AGENT})
    last_error: Exception | None = None
    for attempt in range(3):
        try:
            with urlopen(request, timeout=30) as response:
                return response.read().decode("utf-8")
        except HTTPError as error:
            if error.code == 404:
                raise
            if error.code < 500 or attempt == 2:
                raise BuildError(f"Build source returned HTTP {error.code}: {url}") from error
            last_error = error
        except (URLError, TimeoutError) as error:
            if attempt == 2:
                raise BuildError(f"Could not reach build source: {url}") from error
            last_error = error
        time.sleep(attempt + 1)
    raise BuildError(f"Could not reach build source: {url}") from last_error


def fetch_json(url: str) -> dict:
    try:
        value = json.loads(request_text(url, "application/json"))
    except json.JSONDecodeError as error:
        raise BuildError(f"Build source returned invalid JSON: {url}") from error
    if not isinstance(value, dict):
        raise BuildError(f"Build source returned an invalid JSON envelope: {url}")
    return value


def fetch_html(url: str) -> str | None:
    try:
        html = request_text(url, "text/html")
    except HTTPError as error:
        if error.code == 404:
            return None
        raise
    if "<!doctype html" not in html[:200].lower():
        raise BuildError(f"Build source did not return a complete HTML document: {url}")
    return html


def collect_products(api_base: str, json_loader: Callable[[str], dict]) -> list[dict]:
    products: list[dict] = []
    seen: set[str] = set()
    page = 1
    while True:
        query = urlencode({"pageNum": page, "pageSize": PAGE_SIZE})
        envelope = json_loader(f"{api_base}/products?{query}")
        if envelope.get("code") != 0 or not isinstance(envelope.get("data"), dict):
            raise BuildError("Public product list returned an unsuccessful response")
        data = envelope["data"]
        if data.get("enabled") is False:
            return []
        batch = data.get("products")
        if not isinstance(batch, list):
            raise BuildError("Public product list did not include a products array")
        for product in batch:
            public_uuid = product.get("publicUuid") if isinstance(product, dict) else None
            if not isinstance(public_uuid, str) or not UUID_PATTERN.fullmatch(public_uuid):
                raise BuildError("Public product list included an invalid publicUuid")
            published_at = product.get("publishedAt")
            if not isinstance(published_at, (int, float)) or published_at <= 0:
                raise BuildError(
                    f"Public product is missing its approved online publication timestamp: {public_uuid}"
                )
            normalized_uuid = public_uuid.lower()
            if normalized_uuid not in seen:
                seen.add(normalized_uuid)
                products.append(product)
        if len(batch) < PAGE_SIZE:
            break
        page += 1
    return products


def clear_generated_pages(product_root: Path) -> None:
    if not product_root.exists():
        return
    for directory in product_root.iterdir():
        if not directory.is_dir() or not UUID_PATTERN.fullmatch(directory.name):
            continue
        index = directory / "index.html"
        if index.is_file() and GENERATED_MARKER in index.read_text(encoding="utf-8")[:500]:
            shutil.rmtree(directory)


def iso_timestamp(value: object) -> str | None:
    if not isinstance(value, (int, float)) or value <= 0:
        return None
    return datetime.fromtimestamp(value / 1000, timezone.utc).isoformat().replace("+00:00", "Z")


def generate(
    source_dir: Path,
    json_loader: Callable[[str], dict] = fetch_json,
    html_loader: Callable[[str], str | None] = fetch_html,
) -> int:
    api_base, site_url, baseurl = load_settings(source_dir)
    parsed_api = urlsplit(api_base)
    backend_origin = f"{parsed_api.scheme}://{parsed_api.netloc}"
    route = "/product-showcase/product"
    product_root = source_dir / route.lstrip("/")
    manifest_path = source_dir / "_data" / "product_showcase_pages.json"
    products = collect_products(api_base, json_loader)

    clear_generated_pages(product_root)
    manifest: list[dict] = []
    for product in products:
        public_uuid = product["publicUuid"].lower()
        source_url = f"{backend_origin}/ecommerce-ai-tools{route}/{public_uuid}"
        html = html_loader(source_url)
        if html is None:
            print(f"Skipping product that went offline during the build: {public_uuid}")
            continue
        public_path = f"{route}/{public_uuid}/"
        canonical_url = f"{site_url}{baseurl}{public_path}"
        html = html.replace(source_url, canonical_url)
        if canonical_url not in html:
            raise BuildError(f"Generated page is missing its static canonical URL: {public_uuid}")
        html = html.replace("<!doctype html>", f"<!doctype html>\n{GENERATED_MARKER}", 1)
        destination = product_root / public_uuid / "index.html"
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(html.rstrip() + "\n", encoding="utf-8", newline="\n")

        images = product.get("imageUrls")
        manifest.append(
            {
                "publicUuid": public_uuid,
                "path": public_path,
                "title": product.get("productName") or "Product",
                "lastModified": iso_timestamp(product.get("publishedAt")),
                "image": images[0] if isinstance(images, list) and images else None,
            }
        )

    # The collection root is not a public page. Keep it absent when there are
    # no generated UUID pages so /product-showcase/product/ resolves to 404.
    if product_root.is_dir() and not any(product_root.iterdir()):
        product_root.rmdir()

    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    print(f"Generated {len(manifest)} static product showcase page(s).")
    return len(manifest)


def main() -> int:
    repository_root = Path(__file__).resolve().parents[1]
    try:
        generate(repository_root / "docs")
    except (BuildError, OSError) as error:
        print(f"Product showcase build failed: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
