#!/usr/bin/env python3
"""Generate crawlable product showcase HTML during the Web site build."""

from __future__ import annotations

import json
import re
import shutil
import sys
import time
from datetime import datetime, timezone
from html import escape
from pathlib import Path
from typing import Callable
from urllib.error import HTTPError, URLError
from urllib.parse import urlencode, urlsplit
from urllib.request import Request, urlopen


PAGE_SIZE = 50
UUID_PATTERN = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
    re.IGNORECASE,
)
INLINE_MARKDOWN = re.compile(
    r"(\[([^]]+)]\((https?://[^)\s]+)\)|\*\*([^*\n]+)\*\*|"
    r"__([^_\n]+)__|`([^`\n]+)`|\*([^*\n]+)\*|_([^_\n]+)_)",
)
MARKDOWN_MARKERS = re.compile(
    r"^(?:#{1,6}|>|[-*]|\d+\.)\s+|[`*_~]+|\[([^]]+)]\([^)]+\)",
    re.MULTILINE,
)
LANGUAGE_PATTERN = re.compile(r"^[A-Za-z]{2,3}(?:-[A-Za-z0-9]{2,8})*$")
GENERATED_MARKER = "<!-- generated by scripts/generate_product_showcase_pages.py; do not edit -->"
USER_AGENT = "NexscopeProductShowcaseBuilder/2.0"


class BuildError(RuntimeError):
    """Raised when static product pages cannot be built safely."""


def config_value(config: str, name: str) -> str:
    match = re.search(rf"^{re.escape(name)}:\s*(.+?)\s*$", config, re.MULTILINE)
    if not match:
        raise BuildError(f"Missing {name} in docs/_config.yml")
    return match.group(1).strip().strip("'\"")


def load_settings(source_dir: Path) -> tuple[str, str, str]:
    config = (source_dir / "_config.yml").read_text(encoding="utf-8")
    api_base = config_value(config, "product_showcase_api_base").rstrip("/")
    site_url = config_value(config, "url").rstrip("/")
    baseurl = config_value(config, "baseurl").strip()
    if baseurl and not baseurl.startswith("/"):
        baseurl = "/" + baseurl
    baseurl = baseurl.rstrip("/")
    for label, value in (("product_showcase_api_base", api_base), ("url", site_url)):
        parsed = urlsplit(value)
        if parsed.scheme != "https" or not parsed.netloc:
            raise BuildError(f"{label} must be an absolute HTTPS URL")
    return api_base, site_url, baseurl


def load_template(source_dir: Path) -> str:
    template_path = source_dir.parent / "scripts" / "templates" / "product-showcase-product.html"
    try:
        template = template_path.read_text(encoding="utf-8")
    except OSError as error:
        raise BuildError(f"Could not read product page template: {template_path}") from error
    required = (
        "{{SEO_HEAD}}",
        "{{SEO_CONFIG_JSON}}",
        "{{HTML_LANG}}",
        "{{PRODUCT_NAME}}",
        "{{PRODUCT_DETAILS}}",
        "{{JSON_LD}}",
    )
    missing = [placeholder for placeholder in required if placeholder not in template]
    if missing:
        raise BuildError(f"Product page template is missing: {', '.join(missing)}")
    return template


def request_text(url: str, accept: str) -> str:
    request = Request(url, headers={"Accept": accept, "User-Agent": USER_AGENT})
    last_error: Exception | None = None
    for attempt in range(3):
        try:
            with urlopen(request, timeout=30) as response:
                return response.read().decode("utf-8")
        except HTTPError as error:
            if error.code == 404:
                raise
            if error.code < 500 or attempt == 2:
                raise BuildError(f"Build source returned HTTP {error.code}: {url}") from error
            last_error = error
        except (URLError, TimeoutError) as error:
            if attempt == 2:
                raise BuildError(f"Could not reach build source: {url}") from error
            last_error = error
        time.sleep(attempt + 1)
    raise BuildError(f"Could not reach build source: {url}") from last_error


def fetch_json(url: str) -> dict:
    try:
        value = json.loads(request_text(url, "application/json"))
    except json.JSONDecodeError as error:
        raise BuildError(f"Build source returned invalid JSON: {url}") from error
    if not isinstance(value, dict):
        raise BuildError(f"Build source returned an invalid JSON envelope: {url}")
    return value


def positive_timestamp(value: object) -> int | float | None:
    """Normalize the API's Long timestamp, which may be JSON number or string."""
    if isinstance(value, bool):
        return None
    if isinstance(value, (int, float)):
        return value if value > 0 else None
    if isinstance(value, str) and re.fullmatch(r"[1-9][0-9]*", value.strip()):
        return int(value.strip())
    return None


def collect_products(api_base: str, json_loader: Callable[[str], dict]) -> list[dict]:
    products: list[dict] = []
    seen: set[str] = set()
    page = 1
    while True:
        query = urlencode({"pageNum": page, "pageSize": PAGE_SIZE})
        envelope = json_loader(f"{api_base}/products?{query}")
        if envelope.get("code") != 0 or not isinstance(envelope.get("data"), dict):
            raise BuildError("Public product list returned an unsuccessful response")
        data = envelope["data"]
        if data.get("enabled") is False:
            return []
        batch = data.get("products")
        if not isinstance(batch, list):
            raise BuildError("Public product list did not include a products array")
        for product in batch:
            public_uuid = product.get("publicUuid") if isinstance(product, dict) else None
            if not isinstance(public_uuid, str) or not UUID_PATTERN.fullmatch(public_uuid):
                print(
                    "Skipping invalid public product entry without a valid publicUuid.",
                    file=sys.stderr,
                )
                continue
            published_at = positive_timestamp(product.get("publishedAt"))
            if published_at is None:
                print(
                    "Skipping public product without an approved online publication "
                    f"timestamp: {public_uuid}",
                    file=sys.stderr,
                )
                continue
            product["publishedAt"] = published_at
            normalized_uuid = public_uuid.lower()
            if normalized_uuid not in seen:
                seen.add(normalized_uuid)
                products.append(product)
        if len(batch) < PAGE_SIZE:
            break
        page += 1
    return products


def clear_product_pages(product_root: Path) -> None:
    if not product_root.exists():
        return
    resolved_root = product_root.resolve()
    if resolved_root.name != "product" or resolved_root.parent.name != "product-showcase":
        raise BuildError(f"refusing to clear an unexpected product page path: {resolved_root}")
    shutil.rmtree(resolved_root)


def iso_timestamp(value: object) -> str | None:
    timestamp = positive_timestamp(value)
    if timestamp is None:
        return None
    return datetime.fromtimestamp(timestamp / 1000, timezone.utc).isoformat().replace("+00:00", "Z")


def safe_url(value: object) -> str | None:
    if not isinstance(value, str) or not value.strip():
        return None
    candidate = value.strip()
    parsed = urlsplit(candidate)
    if parsed.scheme != "https" or not parsed.netloc or parsed.username or parsed.password:
        return None
    return candidate


def limited_text(value: object, limit: int) -> str | None:
    if not isinstance(value, str) or not value.strip():
        return None
    normalized = value.strip()
    if len(normalized) <= limit:
        return normalized
    return normalized[: limit - 1].rstrip() + "…"


def plain_markdown(value: object) -> str:
    if not isinstance(value, str):
        return ""
    return re.sub(r"\s+", " ", MARKDOWN_MARKERS.sub(r"\1", value)).strip()


def render_inline(source: str) -> str:
    output: list[str] = []
    cursor = 0
    for match in INLINE_MARKDOWN.finditer(source):
        output.append(escape(source[cursor : match.start()]))
        if match.group(2) is not None and safe_url(match.group(3)):
            output.append(
                f'<a href="{escape(match.group(3), quote=True)}" '
                f'rel="nofollow noopener noreferrer">{escape(match.group(2))}</a>'
            )
        elif match.group(4) is not None or match.group(5) is not None:
            output.append(f"<strong>{escape(match.group(4) or match.group(5))}</strong>")
        elif match.group(6) is not None:
            output.append(f"<code>{escape(match.group(6))}</code>")
        elif match.group(7) is not None or match.group(8) is not None:
            output.append(f"<em>{escape(match.group(7) or match.group(8))}</em>")
        else:
            output.append(escape(match.group(0)))
        cursor = match.end()
    output.append(escape(source[cursor:]))
    return "".join(output)


def product_detail_headings(value: object) -> list[str]:
    if not isinstance(value, str):
        return []
    headings: list[str] = []
    in_code = False
    for line in value.replace("\r", "").split("\n"):
        if line.startswith("```"):
            in_code = not in_code
            continue
        if in_code:
            continue
        match = re.match(r"^#{1,3}\s+(.+)$", line)
        if match:
            label = limited_text(plain_markdown(match.group(1)), 90)
            headings.append(label or f"Section {len(headings) + 1}")
    return headings


def render_markdown(value: object) -> str:
    if not isinstance(value, str) or not value.strip():
        return "<p>No additional product details were provided.</p>"
    lines = value.replace("\r", "").split("\n")
    output: list[str] = []
    index = 0
    heading_number = 0
    while index < len(lines):
        line = lines[index]
        if not line.strip():
            index += 1
            continue
        if line.startswith("```"):
            code: list[str] = []
            index += 1
            while index < len(lines) and not lines[index].startswith("```"):
                code.append(lines[index])
                index += 1
            if index < len(lines):
                index += 1
            output.append(f"<pre><code>{escape(chr(10).join(code))}</code></pre>")
            continue
        heading = re.match(r"^(#{1,3})\s+(.+)$", line)
        if heading:
            heading_number += 1
            level = min(4, len(heading.group(1)) + 1)
            output.append(
                f'<h{level} id="product-detail-section-{heading_number}">'
                f"{render_inline(heading.group(2))}</h{level}>"
            )
            index += 1
            continue
        ordered = re.match(r"^\d+\.\s+(.+)$", line)
        unordered = re.match(r"^[-*]\s+(.+)$", line)
        if ordered or unordered:
            tag = "ol" if ordered else "ul"
            pattern = re.compile(r"^\d+\.\s+(.+)$" if ordered else r"^[-*]\s+(.+)$")
            items: list[str] = []
            while index < len(lines):
                item = pattern.match(lines[index])
                if not item:
                    break
                items.append(f"<li>{render_inline(item.group(1))}</li>")
                index += 1
            output.append(f"<{tag}>{''.join(items)}</{tag}>")
            continue
        if re.match(r"^>\s?.*", line):
            quote: list[str] = []
            while index < len(lines) and re.match(r"^>\s?.*", lines[index]):
                quote.append(re.sub(r"^>\s?", "", lines[index]))
                index += 1
            output.append(f"<blockquote><p>{render_inline(' '.join(quote))}</p></blockquote>")
            continue
        paragraph = [line.strip()]
        index += 1
        while index < len(lines) and lines[index].strip() and not re.match(
            r"^(?:#{1,3}\s+|```|>\s?|[-*]\s+|\d+\.\s+).*$",
            lines[index],
        ):
            paragraph.append(lines[index].strip())
            index += 1
        output.append(f"<p>{render_inline(' '.join(paragraph))}</p>")
    return "".join(output)


def seo_config(product: dict) -> dict:
    raw_config = product.get("seoConfig")
    if isinstance(raw_config, str):
        try:
            raw_config = json.loads(raw_config)
        except json.JSONDecodeError:
            return {}
    return raw_config if isinstance(raw_config, dict) else {}


def seo_metadata(product: dict) -> tuple[str, str, list[str]]:
    product_name = limited_text(product.get("productName"), 120)
    if not product_name:
        raise BuildError("public product is missing its productName")
    config = seo_config(product)
    title = limited_text(config.get("title") or config.get("metaTitle"), 90) or product_name
    description = limited_text(
        config.get("description") or config.get("metaDescription"), 180
    )
    if not description:
        description = f"Explore {product_name} in the Nexscope Product Gallery."
    raw_keywords = config.get("keywords")
    keywords = []
    if isinstance(raw_keywords, str):
        raw_keywords = raw_keywords.split(",")
    if isinstance(raw_keywords, list):
        for value in raw_keywords:
            keyword = limited_text(value, 80)
            if keyword and keyword not in keywords:
                keywords.append(keyword)
            if len(keywords) == 20:
                break
    return title, description, keywords


def seo_language(config: dict) -> str:
    language = limited_text(config.get("language") or config.get("lang"), 35)
    return language if language and LANGUAGE_PATTERN.fullmatch(language) else "en"


def seo_tags(config: dict) -> list[str]:
    raw_tags = config.get("tags")
    if isinstance(raw_tags, str):
        raw_tags = raw_tags.split(",")
    if not isinstance(raw_tags, list):
        return []
    tags: list[str] = []
    seen: set[str] = set()
    for value in raw_tags:
        if not isinstance(value, str):
            continue
        tag = limited_text(" ".join(value.split()), 40)
        if tag and tag.casefold() not in seen:
            tags.append(tag)
            seen.add(tag.casefold())
        if len(tags) == 8:
            break
    return tags


def render_product_outline(headings: list[str]) -> str:
    if len(headings) < 2:
        return ""
    links = "".join(
        f'<li><a href="#product-detail-section-{index}">{escape(heading)}</a></li>'
        for index, heading in enumerate(headings, 1)
    )
    return (
        '<nav class="product-outline" aria-label="Product details contents">'
        '<strong>On this page</strong><ol>' + links + "</ol></nav>"
    )


def configured_canonical(config: dict, canonical_url: str) -> str:
    candidate = safe_url(config.get("canonicalUrl") or config.get("canonical"))
    if candidate and candidate.rstrip("/") == canonical_url.rstrip("/"):
        return candidate
    return canonical_url


def render_seo_head(
    config: dict,
    title: str,
    description: str,
    keywords: list[str],
    canonical_url: str,
    product_name: str,
    first_image: str | None,
) -> str:
    canonical = configured_canonical(config, canonical_url)
    robots = limited_text(config.get("robots"), 200) or (
        "index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1"
    )
    author = limited_text(config.get("author"), 100) or "Nexscope"
    theme_color = limited_text(config.get("themeColor"), 40) or "#fbf9f5"
    open_graph = config.get("openGraph") or config.get("og")
    if not isinstance(open_graph, dict):
        open_graph = {}
    og_title = limited_text(open_graph.get("title") or config.get("ogTitle"), 100) or title
    og_description = limited_text(
        open_graph.get("description") or config.get("ogDescription"), 200
    ) or description
    og_type = limited_text(open_graph.get("type"), 40) or "product"
    og_locale = limited_text(open_graph.get("locale") or config.get("locale"), 35) or "en_US"
    og_site_name = limited_text(
        open_graph.get("siteName") or config.get("siteName"), 100
    ) or "Nexscope Product Gallery"
    og_image = safe_url(open_graph.get("image") or config.get("ogImage")) or first_image
    og_image_alt = limited_text(open_graph.get("imageAlt"), 160) or (
        f"{product_name} product image" if og_image else None
    )

    twitter = config.get("twitter")
    if not isinstance(twitter, dict):
        twitter = {}
    twitter_card = limited_text(twitter.get("card"), 40)
    if twitter_card not in {"summary", "summary_large_image", "app", "player"}:
        twitter_card = "summary_large_image" if og_image else "summary"
    twitter_title = limited_text(twitter.get("title"), 100) or og_title
    twitter_description = limited_text(twitter.get("description"), 200) or og_description
    twitter_image = safe_url(twitter.get("image")) or og_image
    twitter_image_alt = limited_text(twitter.get("imageAlt"), 160) or og_image_alt

    def meta(attribute: str, name: str, content: str) -> str:
        return (
            f'<meta {attribute}="{escape(name, quote=True)}" '
            f'content="{escape(content, quote=True)}">'
        )

    lines = [
        meta("name", "description", description),
        meta("name", "robots", robots),
        meta("name", "author", author),
        meta("name", "theme-color", theme_color),
    ]
    if keywords:
        lines.append(meta("name", "keywords", ", ".join(keywords)))
    lines.extend(
        [
            f'<link rel="canonical" href="{escape(canonical, quote=True)}">',
            meta("property", "og:type", og_type),
            meta("property", "og:locale", og_locale),
            meta("property", "og:site_name", og_site_name),
            meta("property", "og:title", og_title),
            meta("property", "og:description", og_description),
            meta("property", "og:url", canonical),
        ]
    )
    if og_image:
        lines.append(meta("property", "og:image", og_image))
        if og_image_alt:
            lines.append(meta("property", "og:image:alt", og_image_alt))
    lines.extend(
        [
            meta("name", "twitter:card", twitter_card),
            meta("name", "twitter:title", twitter_title),
            meta("name", "twitter:description", twitter_description),
        ]
    )
    if twitter_image:
        lines.append(meta("name", "twitter:image", twitter_image))
        if twitter_image_alt:
            lines.append(meta("name", "twitter:image:alt", twitter_image_alt))
    for key in ("site", "creator"):
        value = limited_text(twitter.get(key), 100)
        if value:
            lines.append(meta("name", f"twitter:{key}", value))

    alternates = config.get("alternates") or config.get("hreflang")
    if isinstance(alternates, dict):
        alternate_items = alternates.items()
    elif isinstance(alternates, list):
        alternate_items = (
            (item.get("language") or item.get("hreflang"), item.get("url") or item.get("href"))
            for item in alternates
            if isinstance(item, dict)
        )
    else:
        alternate_items = ()
    for language, url in alternate_items:
        normalized_language = limited_text(language, 35)
        normalized_url = safe_url(url)
        if normalized_language and normalized_url and (
            normalized_language == "x-default"
            or LANGUAGE_PATTERN.fullmatch(normalized_language)
        ):
            lines.append(
                '<link rel="alternate" '
                f'hreflang="{escape(normalized_language, quote=True)}" '
                f'href="{escape(normalized_url, quote=True)}">'
            )
    return "\n  ".join(lines)


def configured_schema_nodes(config: dict) -> list[dict]:
    values: list[object] = [
        config.get("schema"),
        config.get("structuredData"),
        config.get("jsonLd"),
    ]
    geo = config.get("geo")
    if isinstance(geo, dict):
        values.extend((geo.get("schema"), geo.get("structuredData"), geo.get("jsonLd")))
        if "@type" in geo or "@graph" in geo:
            values.append(geo)

    nodes: list[dict] = []
    for value in values:
        candidates: list[object]
        if isinstance(value, dict) and isinstance(value.get("@graph"), list):
            candidates = value["@graph"]
        elif isinstance(value, list):
            candidates = value
        else:
            candidates = [value]
        for candidate in candidates:
            if isinstance(candidate, dict):
                node = {key: item for key, item in candidate.items() if key not in {"@context", "@graph"}}
                if node:
                    nodes.append(node)
    return nodes


def schema_has_type(node: dict, expected: str) -> bool:
    node_type = node.get("@type")
    if isinstance(node_type, str):
        return node_type == expected
    return isinstance(node_type, list) and expected in node_type


def json_for_html(value: object) -> str:
    return (
        json.dumps(value, ensure_ascii=False, separators=(",", ":"))
        .replace("<", "\\u003c")
        .replace(">", "\\u003e")
        .replace("&", "\\u0026")
    )


def structured_data(
    product: dict,
    title: str,
    description: str,
    canonical_url: str,
    gallery_url: str,
    images: list[str],
    product_url: str | None,
    video_url: str | None,
    language: str,
) -> str:
    product_name = product["productName"]
    product_schema: dict[str, object] = {
        "@type": "Product",
        "@id": canonical_url + "#product",
        "name": product_name,
        "description": description,
        "url": canonical_url,
        "mainEntityOfPage": canonical_url + "#webpage",
    }
    if images:
        product_schema["image"] = images
    if product_url:
        product_schema["sameAs"] = product_url
    published = iso_timestamp(product.get("publishedAt"))
    web_page: dict[str, object] = {
        "@type": "WebPage",
        "@id": canonical_url + "#webpage",
        "url": canonical_url,
        "name": title,
        "description": description,
        "mainEntity": {"@id": canonical_url + "#product"},
        "inLanguage": language,
        "isPartOf": {
            "@type": "CollectionPage",
            "@id": gallery_url + "#collection",
            "name": "Nexscope Product Gallery",
            "url": gallery_url,
        },
    }
    if published:
        web_page["datePublished"] = published
    if images:
        web_page["primaryImageOfPage"] = images[0]
    graph: list[dict[str, object]] = [
        {
            "@type": "Organization",
            "@id": "https://www.nexscope.ai/#organization",
            "name": "Nexscope",
            "url": "https://www.nexscope.ai/",
            "logo": "https://learn.nexscope.ai/logo.png",
        },
        web_page,
        product_schema,
        {
            "@type": "BreadcrumbList",
            "@id": canonical_url + "#breadcrumb",
            "itemListElement": [
                {"@type": "ListItem", "position": 1, "name": "Product Gallery", "item": gallery_url},
                {"@type": "ListItem", "position": 2, "name": product_name, "item": canonical_url},
            ],
        },
    ]
    product_protected = {
        "@context", "@graph", "@id", "@type", "name", "url", "mainEntityOfPage"
    }
    web_page_protected = {
        "@context", "@graph", "@id", "@type", "url", "name", "description",
        "mainEntity", "isPartOf"
    }
    for configured_node in configured_schema_nodes(seo_config(product)):
        if schema_has_type(configured_node, "Product") or "@type" not in configured_node:
            product_schema.update(
                {key: value for key, value in configured_node.items() if key not in product_protected}
            )
        elif schema_has_type(configured_node, "WebPage"):
            web_page.update(
                {key: value for key, value in configured_node.items() if key not in web_page_protected}
            )
        else:
            graph.append(configured_node)
    if images and video_url and re.search(r"\.(?:mp4|webm)(?:[?#].*)?$", video_url, re.I) and published:
        graph.append(
            {
                "@type": "VideoObject",
                "@id": canonical_url + "#video",
                "name": product_name + " product video",
                "description": description,
                "thumbnailUrl": [images[0]],
                "uploadDate": published,
                "contentUrl": video_url,
                "mainEntityOfPage": canonical_url + "#webpage",
            }
        )
    return json_for_html({"@context": "https://schema.org", "@graph": graph})


def render_product_page(template: str, product: dict, canonical_url: str, gallery_url: str) -> str:
    public_uuid = product.get("publicUuid")
    if not isinstance(public_uuid, str) or not UUID_PATTERN.fullmatch(public_uuid):
        raise BuildError("public product detail has an invalid publicUuid")
    published_at = positive_timestamp(product.get("publishedAt"))
    if published_at is None:
        raise BuildError("public product detail is missing its publication timestamp")
    product["publishedAt"] = published_at
    product_name = limited_text(product.get("productName"), 120)
    if not product_name:
        raise BuildError("public product detail is missing its productName")
    product["productName"] = product_name
    config = seo_config(product)
    title, description, keywords = seo_metadata(product)
    language = seo_language(config)
    raw_images = product.get("imageUrls")
    images = []
    if isinstance(raw_images, list):
        images = [url for value in raw_images if (url := safe_url(value))][:5]
    product_url = safe_url(product.get("productUrl"))
    video_url = safe_url(product.get("videoUrl"))
    page_title = title if "nexscope" in title.lower() else f"{title} | Nexscope Product Gallery"
    first_image = images[0] if images else None
    if images:
        preview_stage = '<div class="carousel-stage">' + "".join(
            '<figure class="carousel-slide" data-carousel-slide '
            f'aria-label="Image {index + 1} of {len(images)}">'
            f'<a href="{escape(image, quote=True)}" target="_blank" rel="noopener noreferrer" '
            f'aria-label="Open product image {index + 1} in a new tab">'
            f'<img src="{escape(image, quote=True)}" '
            f'alt="{escape(product_name + " product image " + str(index + 1), quote=True)}" '
            f'loading="{"eager" if index == 0 else "lazy"}" decoding="async"></a></figure>'
            for index, image in enumerate(images)
        ) + '</div>'
    else:
        preview_stage = (
            '<div class="carousel-stage"><div class="media-placeholder"><span>Product image</span>'
            '<strong>No image is currently available.</strong></div></div>'
        )
    carousel_controls = ""
    if len(images) > 1:
        thumbnails = "".join(
            f'<button type="button" class="carousel-thumb" data-carousel-thumb="{index}" '
            f'aria-label="Show image {index + 1} of {len(images)}" '
            f'aria-pressed="{"true" if index == 0 else "false"}">'
            f'<img src="{escape(image, quote=True)}" alt="" loading="lazy" decoding="async"></button>'
            for index, image in enumerate(images)
        )
        carousel_controls = (
            '<div class="carousel-footer"><div class="carousel-arrows">'
            '<button type="button" data-carousel-prev aria-label="Previous image">←</button>'
            '<button type="button" data-carousel-next aria-label="Next image">→</button>'
            '</div><div class="carousel-thumbnails" aria-label="Choose product image">'
            f'{thumbnails}</div></div>'
            '<p class="sr-only" aria-live="polite" data-carousel-announcement></p>'
        )
    video_section = ""
    if video_url:
        if re.search(r"\.(?:mp4|webm)(?:[?#].*)?$", video_url, re.I):
            poster = f' poster="{escape(first_image, quote=True)}"' if first_image else ""
            video_section = (
                '<section class="media-section video-section" aria-labelledby="product-video-title">'
                '<div class="section-heading"><div><span class="eyebrow">Product video</span>'
                '<h2 id="product-video-title">See the product in context.</h2></div>'
                '<p>Use the native controls to play, pause or expand.</p></div>'
                f'<video controls preload="metadata" playsinline src="{escape(video_url, quote=True)}"{poster}></video>'
                "</section>"
            )
        else:
            video_section = (
                '<section class="external-video" aria-labelledby="product-video-title"><div>'
                '<span class="eyebrow">Product video</span><h2 id="product-video-title">Watch the product video.</h2>'
                '<p>The submitted video is hosted on an external website.</p></div>'
                f'<a href="{escape(video_url, quote=True)}" rel="nofollow noopener noreferrer">'
                "Open product video ↗</a></section>"
            )
    source_button = ""
    source_card = ""
    facts_action = ""
    if product_url:
        escaped_product_url = escape(product_url, quote=True)
        source_button = (
            f'<a class="button button-primary" href="{escaped_product_url}" '
            'rel="nofollow sponsored noopener noreferrer">Visit product website ↗</a>'
        )
        host = (urlsplit(product_url).hostname or "Product website").removeprefix("www.")
        source_card = f'<div class="fact"><span>Product source</span><strong>{escape(host)}</strong></div>'
        facts_action = f'<div class="facts-action">{source_button}</div>'
    published = iso_timestamp(product.get("publishedAt"))
    published_card = ""
    if published:
        published_card = (
            '<div class="fact"><span>Published in gallery</span><strong>'
            f'<time datetime="{escape(published, quote=True)}">{escape(published[:10])}</time>'
            "</strong></div>"
        )
    tags = seo_tags(config)
    detail_headings = product_detail_headings(product.get("productDetails"))
    header_tags = (
        '<div class="listing-meta" aria-label="Product tags">'
        + "".join(f'<span class="listing-tag">{escape(tag)}</span>' for tag in tags)
        + "</div>"
        if tags else ""
    )
    media_nav = '<a href="#product-media">Images</a>' if images else ""
    video_nav = '<a href="#product-video-title">Video</a>' if video_url else ""
    replacements = {
        "{{HTML_LANG}}": escape(language, quote=True),
        "{{TITLE}}": escape(page_title),
        "{{DESCRIPTION}}": escape(description),
        "{{SEO_HEAD}}": render_seo_head(
            config,
            title,
            description,
            keywords,
            canonical_url,
            product_name,
            first_image,
        ),
        "{{SEO_CONFIG_JSON}}": json_for_html(config),
        "{{JSON_LD}}": structured_data(
            product,
            title,
            description,
            canonical_url,
            gallery_url,
            images,
            product_url,
            video_url,
            language,
        ),
        "{{GALLERY_URL}}": escape(gallery_url, quote=True),
        "{{PRODUCT_NAME}}": escape(product_name),
        "{{SEO_TAGS}}": header_tags,
        "{{PRODUCT_OUTLINE}}": render_product_outline(detail_headings),
        "{{HEADER_ACTIONS}}": (
            f'<div class="listing-header-actions">{source_button}</div>' if source_button else ""
        ),
        "{{PREVIEW_STAGE}}": preview_stage,
        "{{PREVIEW_COUNTER}}": f"1 / {len(images)}" if images else "No images",
        "{{CAROUSEL_ROLE}}": ' aria-roledescription="carousel"' if len(images) > 1 else "",
        "{{CAROUSEL_CONTROLS}}": carousel_controls,
        "{{PRODUCT_DETAILS}}": render_markdown(product.get("productDetails")),
        "{{PUBLISHED_CARD}}": published_card,
        "{{SOURCE_CARD}}": source_card,
        "{{MEDIA_NAV}}": media_nav,
        "{{VIDEO_NAV}}": video_nav,
        "{{FACTS_ACTION}}": facts_action,
        "{{VIDEO_SECTION}}": video_section,
    }
    html = template
    for placeholder, replacement in replacements.items():
        html = html.replace(placeholder, replacement)
    unresolved = re.findall(r"\{\{[A-Z_]+}}", html)
    if unresolved:
        raise BuildError(f"product page template has unresolved placeholders: {', '.join(sorted(set(unresolved)))}")
    if canonical_url not in html or '"@type":"Product"' not in html:
        raise BuildError("rendered product page failed its SEO validation")
    return html.replace("<!doctype html>", f"<!doctype html>\n{GENERATED_MARKER}", 1).rstrip() + "\n"


def generate(
    source_dir: Path,
    json_loader: Callable[[str], dict] = fetch_json,
    detail_loader: Callable[[str], dict] | None = None,
) -> int:
    api_base, site_url, baseurl = load_settings(source_dir)
    template = load_template(source_dir)
    route = "/product-showcase/product"
    product_root = source_dir / route.lstrip("/")
    manifest_path = source_dir / "_data" / "product_showcase_pages.json"

    clear_product_pages(product_root)
    manifest_path.unlink(missing_ok=True)

    products = collect_products(api_base, json_loader)
    load_detail = detail_loader or json_loader
    manifest: list[dict] = []
    gallery_url = f"{site_url}{baseurl}/product-showcase/"
    for summary in products:
        public_uuid = summary["publicUuid"].lower()
        public_path = f"{route}/{public_uuid}/"
        canonical_url = f"{site_url}{baseurl}{public_path}"
        try:
            envelope = load_detail(f"{api_base}/products/{public_uuid}")
            if envelope.get("code") != 0 or not isinstance(envelope.get("data"), dict):
                raise BuildError("public product detail returned an unsuccessful response")
            product = dict(envelope["data"])
            if str(product.get("publicUuid", "")).lower() != public_uuid:
                raise BuildError("public product detail UUID does not match the requested product")
            static_html = render_product_page(template, product, canonical_url, gallery_url)
        except (BuildError, HTTPError, URLError, TimeoutError, UnicodeError, ValueError) as error:
            print(f"Skipping product page {public_uuid}: {error}", file=sys.stderr)
            continue

        destination = product_root / public_uuid / "index.html"
        destination.parent.mkdir(parents=True, exist_ok=True)
        temporary_destination = destination.with_suffix(".html.tmp")
        try:
            temporary_destination.write_text(static_html, encoding="utf-8", newline="\n")
            temporary_destination.replace(destination)
        finally:
            temporary_destination.unlink(missing_ok=True)

        images = product.get("imageUrls")
        valid_images = [url for value in images if (url := safe_url(value))] if isinstance(images, list) else []
        manifest.append(
            {
                "publicUuid": public_uuid,
                "path": public_path,
                "title": product.get("productName") or "Product",
                "lastModified": iso_timestamp(product.get("publishedAt")),
                "image": valid_images[0] if valid_images else None,
            }
        )

    if product_root.is_dir() and not any(product_root.iterdir()):
        product_root.rmdir()

    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    print(f"Generated {len(manifest)} static product showcase page(s).")
    return len(manifest)


def main() -> int:
    repository_root = Path(__file__).resolve().parents[1]
    try:
        generate(repository_root / "docs")
    except (BuildError, OSError) as error:
        print(f"Product showcase build failed: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
